/*
 *  This file is part of BlackHole (https://github.com/Sangwan5688/BlackHole).
 * 
 * BlackHole is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BlackHole is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with BlackHole.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Copyright (c) 2021-2022, Ankit Sangwan
 */

class ConstantCodes {
  static const Map<String, String> countryCodes = {
    'Argentina': 'ar',
    'Austria': 'at',
    'Australia': 'au',
    'Belgium': 'be',
    'Bulgaria': 'bg',
    'Bolivia': 'bo',
    'Brazil': 'br',
    'Canada': 'ca',
    'Chile': 'cl',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Estonia': 'ee',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Guatemala': 'gt',
    'Hong Kong': 'hk',
    'Honduras': 'hn',
    'Hungary': 'hu',
    'Indonesia': 'id',
    'Ireland': 'ie',
    'Israel': 'il',
    'India': 'in',
    'Iceland': 'is',
    'Italy': 'it',
    'Japan': 'jp',
    'Korea': 'kr',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Latvia': 'lv',
    'Morocco': 'ma',
    'Mexico': 'mx',
    'Malaysia': 'my',
    'Nicaragua': 'ni',
    'Netherlands': 'nl',
    'Norway': 'no',
    'New Zealand': 'nz',
    'Panama': 'pa',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Paraguay': 'py',
    'Romania': 'ro',
    'Russian Federation': 'ru',
    'Saudi Arabia': 'sa',
    'Sweden': 'se',
    'Singapore': 'sg',
    'Spain': 'es',
    'South Africa': 'za',
    'Slovakia': 'sk',
    'Switzerland': 'ch',
    'Thailand': 'th',
    'Turkey': 'tr',
    'Taiwan': 'tw',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Uruguay': 'uy',
    'Vietnam': 'vn'
  };

  // supported local charts and their codes
  static const Map<String, String> localChartCodes = {
    'Global': '37i9dQZEVXbMDoHDwVN2tF',
    'Argentina': '37i9dQZEVXbMMy2roB9myp',
    'Australia': '37i9dQZEVXbJPcfkRz0wJ0',
    'Austria': '37i9dQZEVXbKNHh6NIXu36',
    'Belarus': '37i9dQZEVXbIYfjSLbWr4V',
    'Belgium': '37i9dQZEVXbJNSeeHswcKB',
    'Bolivia': '37i9dQZEVXbJqfMFK4d691',
    'Brazil': '37i9dQZEVXbMXbN3EUUhlg',
    'Bulgaria': '37i9dQZEVXbNfM2w2mq1B8',
    'Canada': '37i9dQZEVXbKj23U1GF4IR',
    'Chile': '37i9dQZEVXbL0GavIqMTeb',
    'Colombia': '37i9dQZEVXbOa2lmxNORXQ',
    'Costa Rica': '37i9dQZEVXbMZAjGMynsQX',
    'Czeck Republic': '37i9dQZEVXbIP3c3fqVrJY',
    'Denmark': '37i9dQZEVXbL3J0k32lWnN',
    'Dominican Republic': '37i9dQZEVXbKAbrMR8uuf7',
    'Ecuador': '37i9dQZEVXbJlM6nvL1nD1',
    'Egypt': '37i9dQZEVXbJqdarpmTJDL',
    'El Salvador': '37i9dQZEVXbLxoIml4MYkT',
    'Estonia': '37i9dQZEVXbLesry2Qw2xS',
    'Finland': '37i9dQZEVXbMxcczTSoGwZ',
    'France': '37i9dQZEVXbIPWwFssbupI',
    'Germany': '37i9dQZEVXbJiZcmkrIHGU',
    'Greece': '37i9dQZEVXbJqdarpmTJDL',
    'Guatemala': '37i9dQZEVXbLy5tBFyQvd4',
    'Honduras': '37i9dQZEVXbJp9wcIM9Eo5',
    'Hong Kong': '37i9dQZEVXbLwpL8TjsxOG',
    'Hungary': '37i9dQZEVXbNHwMxAkvmF8',
    'Iceland': '37i9dQZEVXbKMzVsSGQ49S',
    'India': '37i9dQZEVXbLZ52XmnySJg',
    'Indonesia': '37i9dQZEVXbObFQZ3JLcXt',
    'Ireland': '37i9dQZEVXbKM896FDX8L1',
    'Israel': '37i9dQZEVXbJ6IpvItkve3',
    'Italy': '37i9dQZEVXbIQnj7RRhdSX',
    'Japan': '37i9dQZEVXbKXQ4mDTEBXq',
    'Kazakhstan': '37i9dQZEVXbM472oKPNKzS',
    'Latvia': '37i9dQZEVXbJWuzDrTxbKS',
    'Lithuania': '37i9dQZEVXbMx56Rdq5lwc',
    'Luxembourg': '37i9dQZEVXbKGcyg6TFGx6',
    'Malaysia': '37i9dQZEVXbJlfUljuZExa',
    'Mexico': '37i9dQZEVXbO3qyFxbkOE1',
    'Morocco': '37i9dQZEVXbJqdarpmTJDL',
    'Netherlands': '37i9dQZEVXbKCF6dqVpDkS',
    'New Zealand': '37i9dQZEVXbM8SIrkERIYl',
    'Nicaragua': '37i9dQZEVXbISk8kxnzfCq',
    'Nigeria': '37i9dQZEVXbKY7jLzlJ11V',
    'Norway': '37i9dQZEVXbJvfa0Yxg7E7',
    'Pakistan': '37i9dQZEVXbJkgIdfsJyTw',
    'Panama': '37i9dQZEVXbKypXHVwk1f0',
    'Paraguay': '37i9dQZEVXbNOUPGj7tW6T',
    'Peru': '37i9dQZEVXbJfdy5b0KP7W',
    'Philippines': '37i9dQZEVXbNBz9cRCSFkY',
    'Poland': '37i9dQZEVXbN6itCcaL3Tt',
    'Portugal': '37i9dQZEVXbKyJS56d1pgi',
    'Romania': '37i9dQZEVXbNZbJ6TZelCq',
    'Saudi Arabia': '37i9dQZEVXbLrQBcXqUtaC',
    'Singapore': '37i9dQZEVXbK4gjvS1FjPY',
    'Slovakia': '37i9dQZEVXbKIVTPX9a2Sb',
    'South Africa': '37i9dQZEVXbMH2jvi6jvjk',
    'South Korea': '37i9dQZEVXbNxXF4SkHj9F',
    'Spain': '37i9dQZEVXbNFJfN1Vw8d9',
    'Sweden': '37i9dQZEVXbLoATJ81JYXz',
    'Switzerland': '37i9dQZEVXbJiyhoAPEfMK',
    'Taiwan': '37i9dQZEVXbMnZEatlMSiu',
    'Thailand': '37i9dQZEVXbMnz8KIWsvf9',
    'Turkey': '37i9dQZEVXbIVYVBNw9D5K',
    'Ukraine': '37i9dQZEVXbKkidEfWYRuD',
    'UAE': '37i9dQZEVXbM4UZuIrvHvA',
    'United Kingdom': '37i9dQZEVXbLnolsZ8PSNw',
    'USA': '37i9dQZEVXbLRQDuF5jeBp',
    'Uruguay': '37i9dQZEVXbMJJi3wgRbAy',
    'Venezuela': '37i9dQZEVXbJ6IpvItkve3',
    'Vietnam': '37i9dQZEVXbLdGSmz6xilI'
  };

  // supported languages and their code
  static const Map<String, String> languageCodes = {
    'English': 'en',
    'Belarusian': 'be',
    'Chinese': 'zh',
    'Czech': 'cs',
    'Dutch': 'nl',
    'French': 'fr',
    'German': 'de',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hungarian': 'hu',
    'Indonesian': 'id',
    'Italian': 'it',
    'Korean': 'ko',
    'Malayalam': 'ml',
    'Nepali': 'ne',
    'Polish': 'pl',
    'Portuguese': 'pt',
    'Punjabi': 'pa',
    'Russian': 'ru',
    'Spanish': 'es',
    'Tamil': 'ta',
    'Turkish': 'tr',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
  };
}
